In [5]:
import numpy

In [6]:
n = 5
a = numpy.zeros((n, n))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
x = y = 2
i = 1
a[x, y] = i
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
end = 2
for end in range(n//2, n):
    while x < end:
        x += 1
        i += 1
        a[x, y] = i
        print(a)
        print()
    while y < end:
        y += 1
        i += 1
        a[x, y] = i
        print(a)
        print()
    while x > n - end - 1:
        x -= 1
        i += 1
        a[x, y] = i
        print(a)
        print()
    while y > n - end - 1:
        y -= 1
        i += 1
        a[x, y] = i
        print(a)
        print()
while x < n:
        x += 1
        i += 1
        a[x, y] = i
        print(a)
        print()
    



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 4. 0.]
 [0. 0. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 1. 4. 0.]
 [0. 0. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 6. 5. 0.]
 [0. 0. 1. 4. 0.]
 [0. 0. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 7. 6. 5. 0.]
 [0. 0. 1. 4. 0.]
 [0. 0. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 7. 6. 5. 0.]
 [0. 8. 1. 4. 0.]
 [0. 0. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 7. 6. 5. 0.]
 [0. 8. 1. 4. 0.]
 [0. 9. 2. 3. 0.]
 [0. 0. 0. 0. 0.]]

[[ 0.  0.  0.  0.  0.]
 [ 0.  7.  6.  5.  0.]
 [ 0.  8.  1.  4.  0.]
 [ 0.  9.  2.  3.  0.]
 [ 0. 10.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.]
 [ 0.  7.  6.  5.  0.]
 [ 0.  8.  1.  4.  0.]
 [ 0.  9.  2.  3.  0.]
 [ 0. 10. 11.  0.  0.]]

[[ 0.  0.  0.  0.  0.]
 [ 0.  

IndexError: index 5 is out of bounds for axis 0 with size 5